### ISSUE TITLE
Released version does detect Notebook installed from Anaconda

### ISSUE THREAD

**Issue by spinicist** [jupyterlab/jupyterlab_app#126]
Hi,

Thanks for building this - I've never been a fan of running Notebooks through the browser so the App is a great development.

I've installed version 0.1.1 on Mac OS (El Capitan), which has an up to date Anaconda install as well (Notebook version 4.3.0). When starting the app it complains that it cannot find Jupyter, but if I manually navigate to the anaconda/bin directory and tell it to look there, everything starts fine.

The only thing I can think of is that I run Zsh, not bash. The path for Anaconda is only in my .zsh_rc file. How does Jupyterlab App try to pick up the path variable?

**Comment by ddavidebor** [comment]
Hi,

The apps spawns the notebook indeed through Bash, so it will not look for Anaconda in .zsh?rc

https://github.com/jupyterlab/jupyterlab_app/blob/6d67cd254b00ab564d58007ad0b53f08e07bafa5/src/main/server.ts#L65

**Comment by lucbouchard1** [comment]
Hi @spinicist,

I'm glad you're finding our project useful. As @ddavidebor, we currently pick up your PATH variable by spawning a bash shell. However, we are currently the process of making that system more robust. Most importantly, the app will persist any paths the user enters manually, so you will only have to enter it once.

I hope to get some PR's in for that feature in the next week or so. Let me know if you have any questions!

**Comment by spinicist** [comment]
Why specifically bash, and not the user's default shell? I don't think the actual line of code passed to spawn the notebook is bash-specific from looking at it. I also realised that it wasn't picking up PYTHONPATH, so I couldn't access my modules.

As a work-around, I am now launching the App from the command-line with ```open /Applications/JupyterLab.app```, which works, so I will close this for now.

Now I just need IPython Widgets to work out of the box and I'm all set ;)

**Comment by lucbouchard1** [comment]
We could try to launch the user's default shell, but frankly, launching a shell to pick up the environment variables has proven to be really unreliable, and it is kind of a hack that we're trying to move away from.

I've already started implementing "smart" python environment detection that falls back on environment variables or user input only when absolutely necessary. I think this will give us a much more robust base to build off of that will lead to a better application.
