### ISSUE TITLE
ipywidgets fail to be displayed on app

### ISSUE THREAD

**Issue by mofeing** [jupyterlab/jupyterlab_app#132]
Hi everyone,
I have a little problem while working with the app. So I have a few simple notebooks with some ipywidgets and they work perfectly fine when running the JupyterLab in the browser but fail when are run on the app. I get this message:
> 
> Failed to display Jupyter Widget of type Dropdown.
> If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the [Jupyter Widgets Documentation](https://ipywidgets.readthedocs.io/en/stable/user_install.html) for setup instructions.
> If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.

I've already followed the instructions on the Jupyter Widgets Documentation but nothing has changed.

Any guess?

Thanks in advanced.

**Comment by blink1073** [comment]
Hi @mofeing, Jupyter Widgets are not yet compatible with our Electron app.  We don't have an extension system in place for it yet.

**Comment by mofeing** [comment]
Ok, I thought it was something like that but wasn't sure.
Thanks @blink1073
