### ISSUE TITLE
Upgrade JupyterLab packages

### ISSUE THREAD

**Issue by Wietsedv** [jupyterlab/jupyterlab_app#135]
JypyterLab_app (this native app) is made using the NPM JupyterLab packages, but the packages are outdated. Currently the 0.9.x versions of the packages are used while the most recent versions are 0.15.x. This means that JupyterLab_app is now equivalent to version 0.26.x (7 Aug. 2017) of JupyterLab.

I am well aware that the NPM packages are not (api) stable yet, and this is probably the reason the packages are not upgraded yet. But the current 0.15 versions must be a lot closer the final 1.0 release than 0.9.

I am already working on a PR (that is becoming pretty large) which upgrades to the same package versions as JupyterLab 0.31.2. This PR will contain contain multiple fixes, workarounds and minimal refactorings. I will create a PR and motivate my choices when JypyterLab_app is fully working again.

**Comment by declanvk** [comment]
Hey @Wietsedv,
I'm also working on a branch towards this same goal. If you would like to collaborate, I have some [initial changes in place here](https://github.com/declanvk/jupyterlab_app/tree/upgrade_jupyterlab_beta_release). 

Thanks,
Declan.

**Comment by Wietsedv** [comment]
That's great! I think my version is further completed. I'll push my version and I will compare/merge our branches tomorrow.

**Comment by declanvk** [comment]
Closed by #137
