### ISSUE TITLE
Return character ignored

### ISSUE THREAD

**Issue by db87** [jupyterlab/jupyterlab_app#145]
It seems that the '\r' character is ignored when printing stdout:

![image](https://user-images.githubusercontent.com/1877777/36577591-1dee1dc2-18a8-11e8-9dcb-7ae94645c070.png)

This should just display '9'. I'm using version 0.22.1.

**Comment by declanvk** [comment]
@db87 I think this might be a behavior that belongs to jupyter notebooks in general. Have you tried this in the browser and achieved the results that you expected?

**Comment by db87** [comment]
It works as expected in browser Jupyter notebooks. Various progress bar libraries and such rely on it. Otherwise I get outputs that fill the screen like this:
![image](https://user-images.githubusercontent.com/1877777/37315144-0c1551d4-26a8-11e8-9dc9-3ba276cafb06.png)

**Comment by declanvk** [comment]
I think if you update to using the latest version of JupyterLab you'll find that issue has been fixed:
![2018-03-12 19 59 36](https://user-images.githubusercontent.com/7276122/37320261-200b7f60-2630-11e8-9fcd-e3bdd3abbac4.gif)

However, currently a packaged build of the latest release is not yet available. In the meantime I would recommend building from source, if that works for you. Sorry about the inconvenience, hope to have a release soon.

**Comment by db87** [comment]
That's great, thanks!
