### ISSUE TITLE
Missing common menubar buttons on Windows

### ISSUE THREAD

**Issue by declanvk** [jupyterlab/jupyterlab_app#154]
In the windows version of the app, the common buttons such as Close, Fullscreen, or Minimize are missing from the menubar.

<img width="960" alt="packagedjupyterlab" src="https://user-images.githubusercontent.com/7276122/37310880-9f88049e-2602-11e8-8a46-94a60eac1206.PNG">

**Comment by waio1990** [comment]
Hi, im running the electron app using npm run, and I also have no buttons, and cant move the window. 

I wish the documentation on how to run this app would be clearer, as i'm no expert on electron and figuring it out has proven a masive time investment.
