### ISSUE TITLE
White bar stays at top of screen in fullscreen mode on OSX

### ISSUE THREAD

**Issue by JohnPaton** [jupyterlab/jupyterlab_app#156]
In fullscreen mode on OSX, the white bar at the top of the window is still visible when the app is in full screen mode. I think the bar shouldn't be visible, especially since it's the only white element on an otherwise dark screen when using the dark theme.

Non-full screen mode:
![screen shot 2018-03-28 at 10 56 37](https://user-images.githubusercontent.com/18459252/38018975-b76379ec-3276-11e8-8555-0f47c685385a.png)

Full screen mode (note the white border at the top of the image):
![screen shot 2018-03-28 at 10 55 30](https://user-images.githubusercontent.com/18459252/38018923-978816be-3276-11e8-90b3-edb9a664a4c5.png)

**Comment by declanvk** [comment]
Waiting on electron/electron#12592
