### ISSUE TITLE
Investigate electron-remote

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab_app#16]
Looks like this could be very useful in talking between the two processes:

https://github.com/electron-userland/electron-remote

**Comment by ddavidebor** [comment]
@ellisonbg these are the official APIs https://electron.atom.io/docs/api/remote/ they're included in Electron. They're absolutely fundamental 👍

**Comment by ddavidebor** [comment]
@ellisonbg i think we can close this
