### ISSUE TITLE
Misleading project description: "native"?

### ISSUE THREAD

**Issue by hyiltiz** [jupyterlab/jupyterlab_app#172]
How is an Electron based app qualify as "native"? Native doesn't mean "not opened from within your already installed browser", esp. since Electron is essentially just another browser. Native should mean whatever the OS and the desktop environment provides as standard shared libraries/APIs.

**Comment by afshin** [comment]
Thanks for the feedback. Native in this context means the app runs as a desktop application.

**Comment by hyiltiz** [comment]
Then wouldn't it prevent some confusion by simply saying it "a desktop application"?

**Comment by jasongrout** [comment]
I like your wording "desktop application" and have opened a PR: https://github.com/jupyterlab/jupyterlab_app/pull/173. What do you think, @afshin?
