### ISSUE TITLE
Here's an alternative solution

### ISSUE THREAD

**Issue by adammenges** [jupyterlab/jupyterlab_app#174]
Not sure what the status of this is, I don't see many commits hitting over the past few years. So, I made this simple alternative. Honestly does everything I wanted from an app.

https://github.com/adammenges/JupyterLabApp

It allows me to have an app to switch to instead on hutting around my tab bar, more screen real estate saved, and most importantly let's me override keyboard short cuts that would otherwise be reserved for the browser:

``` json
{
    "shortcuts": [
        {
            "command": "application:activate-next-tab",
            "keys": [
                "Accel Shift ]"
            ],
            "selector": "body"
        },
        {
            "command": "application:activate-previous-tab",
            "keys": [
                "Accel Shift ["
            ],
            "selector": "body"
        }
    ]
}
```

Anyway, maybe someone else will find this helpful. Mainly build it for macOS, but should work fine on windows / linux too.

**Comment by mbektas** [comment]
We upgraded the App to JupyterLab 3. master branch has the latest updates.
