### ISSUE TITLE
Why is it abandoned?

### ISSUE THREAD

**Issue by s-valent** [jupyterlab/jupyterlab_app#181]
Such a great idea, but not working anymore

**Comment by vidartf** [comment]
I think mostly due to a lack of time for maintainers. If you or anyone else wants to volunteer time to help maintain this, I think that would be very welcome! Who better to maintain it than someone who wants to use it themselves? :)

**Comment by mbektas** [comment]
@s-valent we upgraded the App to JupyterLab 3. master branch has the latest updates.
