### ISSUE TITLE
Can't use terminals on jupyterlab

### ISSUE THREAD

**Issue by Mithil467** [jupyterlab/jupyterlab_app#211]
## Description

Terminal seems to be disabled.
![image](https://user-images.githubusercontent.com/41439841/133549099-3e1c6fa4-9c50-4e1d-8a6c-a0fb44f3ff05.png)

Opening browser console with "Ctrl+Shift+i" shows this error in `Disabling terminals plugin because they are not available on the server`.

 From my experience, this happens when [tornado](https://pypi.org/project/tornado/) is not installed.

## Reproduce

1. Install jupyterlab app.
2. Run it.

## Expected behavior

![image](https://user-images.githubusercontent.com/41439841/133549149-fb48c2b7-bd5b-4f41-ab39-0c7103222d10.png)

## Context

- Operating System and version: Windows 10
- JupyterLab version: Latest installer on github actions https://github.com/jupyterlab/jupyterlab_app/actions/runs/1239871781

<details><summary>Browser Output</summary>

<pre>
Disabling terminals plugin because they are not available on the server
</pre>
</details>

**Comment by mbektas** [comment]
Thanks for testing @Mithil467! This seems to be affecting only Windows version. Looking into it.
