### ISSUE TITLE
Signed electron app on Mac O/S

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/jupyterlab_app#227]
Installing on Mac o/s, I notice that you haven't signed/notarised the app, so a naive attempt at installing the app by double clicking the download fails:

![image](https://user-images.githubusercontent.com/82988/134425115-a8d53a5c-9fa8-48bf-b9d9-6e7c60bb92d4.png)

Viewing the download and right-clicking allows you to open the package and from there enter the installation process:

![image](https://user-images.githubusercontent.com/82988/134425169-f5e009ff-1bf0-41cc-8530-465748037b7e.png)

*I also note the install step requires a user authentication step to grant some sort of permissions to the app.*

Re: signing/notarising the app for use on Mac, I note that @simonw seems to have gone through a discovery process about how to do this recently in the context of the `datasette-app`: https://github.com/simonw/datasette-app/issues?q=is%3Aissue+signing+

**Comment by krassowski** [comment]
Duplicate of #202?

**Comment by psychemedia** [comment]
Oops... sorry for duplicating.
