### ISSUE TITLE
"Jupyter Server Not Found" on Windows 10

### ISSUE THREAD

**Issue by shayandavoodii** [jupyterlab/jupyterlab_app#241]
tried to open **jupyterLab.exe** for second time and I encountered this error:
![image](https://user-images.githubusercontent.com/52105833/134666407-f89f686b-88e3-4522-a59c-5d0236202fb2.png)
first time that I lunched **jupyterLab.exe** there wasn't any kind of problem there even I wrote few lines of codes and there wasn't problem. But second time I encountered with this error. How can I fix this? why this happens?

-----------------------
***Note That** my jupyter-notebook version is higher than 4.3.0 and python has been added to path.
JupyterLab Version : 3.1.12-2

**Comment by mbektas** [comment]
Hi @shayandavoodii , thanks for reporting this. We are looking into it. As a workaround can you try running is as administrator. Right click JupyterLab launcher icon and choose `Run as administrator`.

**Comment by shayandavoodii** [comment]
> Hi @shayandavoodii , thanks for reporting this. We are looking into it. As a workaround can you try running is as administrator. Right click JupyterLab launcher icon and choose `Run as administrator`.

Hi, Thanks for your response and support.  
I tried `Run as administrator`, Then JupyterLab lunched without any problem!
we have to lunch it as administrator always?

**Comment by mbektas** [comment]
We hope to fix the issue in the newer versions so you won't have to run as administrator. Please use it as a workaround for now.

**Comment by shayandavoodii** [comment]
> We hope to fix the issue in the newer versions so you won't have to run as administrator. Please use it as a workaround for now.

Thanks. As a **recommendation**, can you add possibility of automatic closing brackets?  
I mean when you open parenthesis `(`, jupyterlab editor close the parenthesis `)` automatically.

**Comment by krassowski** [comment]
@shayandavoodii to enable auto-closing brackets you can go to the topbar menu "Settings" and toggle the "Auto Close Brackets" option (second from the bottom on the screenshot below):

![Screenshot from 2021-08-11 13-00-07](https://user-images.githubusercontent.com/5832902/129025113-bef5634e-2ccc-4d64-b6ad-5c333e686e99.png)

For other general JupyterLab questions please try to search the issues in the main JupyterLab repo first: https://github.com/jupyterlab/jupyterlab/issues

**Comment by shayandavoodii** [comment]
> @shayandavoodii to enable auto-closing brackets you can go to the topbar menu "Settings" and toggle the "Auto Close Brackets" option (second from the bottom on the screenshot below):
> 
> ![Screenshot from 2021-08-11 13-00-07](https://user-images.githubusercontent.com/5832902/129025113-bef5634e-2ccc-4d64-b6ad-5c333e686e99.png)
> 
> For other general JupyterLab questions please try to search the issues in the main JupyterLab repo first: https://github.com/jupyterlab/jupyterlab/issues

Dear @krassowski, Thanks for your help.  
I'm sorry mentioning my recommendation here! surly I'll follow instructions from now on.
Thanks again.

**Comment by ryilkici** [comment]
> Hi @shayandavoodii , thanks for reporting this. We are looking into it. As a workaround can you try running is as administrator. Right click JupyterLab launcher icon and choose `Run as administrator`.

Dear @mbektas I tried run as administrator but it didn't work for me. And I tried to reinstall the app but nothing has changed. Do you have different solutions for this issue?

Thanks,

**Comment by umernalla** [comment]
Hi @ryilkici ,
I had the same issue as you - was installing for me only.
When I selected the 'install for all users' and accepted the default directory for JupyterLab - then it seemed to work.
But it does not let me change the working directory - so probably going back to browser-based usage...
