### ISSUE TITLE
Parenthesis/bracket auto-complete

### ISSUE THREAD

**Issue by mkayanda** [jupyterlab/jupyterlab_app#249]
I might be missing something, but noticed that when I type a bracket on the app, for example print(), it doesn't autocomplete the second bracket like it works on localhost API. You have to type the second parenthesis. I wonder if that can be incorporated. 

Maybe, I am just a lazy programmer.

**Comment by krassowski** [comment]
@mkayanda to enable auto-complete of brackets you can go to the topbar menu "Settings" and toggle the "Auto Close Brackets" option (second from the bottom on the screenshot below):

![Screenshot from 2021-08-11 13-00-07](https://user-images.githubusercontent.com/5832902/129025113-bef5634e-2ccc-4d64-b6ad-5c333e686e99.png)

For other general JupyterLab questions please try to search the issues in the main JupyterLab repo first: https://github.com/jupyterlab/jupyterlab/issues (I already answered this question twice over there and once in this repo) - but if you find anything which works in JupyterLab but not in jupyterlab-app then this is the right repo to open issues :)

**Comment by mkayanda** [comment]
@krassowski thank you for the reply. I had not checked thoroughly through the issues. Loving the app.
