### ISSUE TITLE
Dark Theme option not working on macOS Big Sur 11.6

### ISSUE THREAD

**Issue by AndrewKostandy** [jupyterlab/jupyterlab_app#253]
## Description

Dark Theme option not working on macOS Big Sur 11.6

## Reproduce

1. Go to Settings -> JupyterLab Theme
2. Click on JupyterLab Dark
3. Nothing happens

## Expected behavior

Dark Theme visible

## Context

- Operating System and version: macOS Big Sur 11.6
- JupyterLab version: 3.1.12-2

**Comment by mbektas** [comment]
Thanks for reporting this @AndrewKostandy . I am not able to reproduce the issue.
1. Have you made any customizations to your installation?
2. Do you see any error messages in App's Browser Console? You can check using App's macOS menu -> View -> Toggle Developer Tools and check Console tab in there.

**Comment by wooters** [comment]
It seems to be working for me. I'm also on Big Sur 11.6 and using the same JupyterLab version (3.1.12-2). 

Could it be that you installed it for all users instead of [Install for me only](https://github.com/jupyterlab/jupyterlab_app/blob/master/env-customization-guide.md#macos-instructions). Just guessing...

**Comment by AndrewKostandy** [comment]
Yes, I had installed for all users. I've just deleted and installed the app again for me only but it still doesn't work.

I followed the steps above by @mbektas. When toggling Dark Theme I get the following errors:

PUT http://localhost.... 500 (Internal Server Error)

Uncaught (in promise) Error: Invalid response: 500
Internal Server Error
at SettingManager.save
at async SettingConnector.save
at async SettingRegistry._save

**Comment by mbektas** [comment]
@AndrewKostandy appears like you don't have permission to save settings file. Theme Settings would be saved in `/Users/<your_username>/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings`. You can check if there are any permission issues along this path.

**Comment by AndrewKostandy** [comment]
Thanks @mbektas. I  had the folder: /Users/<your_username>/.jupyter but it had only 1 file called "migrated" and not a "lab" folder. I checked the permissions of the folder and my username wasn't even listed. After deleting the .jupyter folder (it asked for my password in the process) and reopening JupyterLab, it recreated the folder but with the correct permissions. I can now switch to Dark Theme successfully.

I believe that may have happened because I initially installed the app for all users. Deleting the app and reinstalling it could not fix the permissions for the pre-existing folder.

Thanks again!

**Comment by mbektas** [comment]
Glad to hear it is working now @AndrewKostandy !
