### ISSUE TITLE
Open currrent folder from command line

### ISSUE THREAD

**Issue by popcornylu** [jupyterlab/jupyterlab_app#256]
### Problem

Nice project. It would be good to open jupyterlab from terminal and set the workspace from the launched directory. (just like vscode provides)

Usage
```
$ jupyterlab_app .
```

Reference 
https://code.visualstudio.com/docs/setup/mac

**Comment by mbektas** [comment]
Thanks @popcornylu! this is a great idea that we will consider to support.

**Comment by fperez** [comment]
This is a great idea (I use this in VSCode all the time), and as part of the same functionality it should support also opening directly a single file from the cmd line, i.e. `jupyterlab_app foo.ipynb` or `jupyterlab_app foo.py`.

Thanks for the great work!

**Comment by ZorkJ** [comment]
Nice Projects! I have a question: how to change the working directory?

**Comment by krassowski** [comment]
> how to change the working directory?

I imagine it would be easy to make the default root directory configurable in the settings. I think that the occurrences of `app.getPath('home')` would need to be replace by a configurable string in the first step, and then we should allow the startup script to overwrite it with the path passed on startup from command line (and maybe to remember the last working directory too?). I don't know however how if this should connect to the idea of workspaces in any way.

**Comment by unifey** [comment]
> Nice Projects! I have a question: how to change the working directory?

For now, I created a hard link in the home directory and use that to move to the working directory I want to use.
