### ISSUE TITLE
Searching in all cells

### ISSUE THREAD

**Issue by NILICK** [jupyterlab/jupyterlab_app#267]
It seems in Jupyterlab-app, we can search only in a cell and not all project, but in classic jupyterlab that open in browser we can search in all cells. I think, the capability searching in all cells is important.

**Comment by krassowski** [comment]
Search (and replace) in all cells is available in JupyterLab and in jupyterlab-app/desktop:

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/qdXOY.gif

Please ensure that you are using the latest version (https://github.com/jupyterlab/jupyterlab_app/releases/tag/v3.1.13-1).

**Comment by NILICK** [comment]
Thanks for your prompt response. I think I must reinstall jupyterlab-app.

**Comment by NILICK** [comment]
I reinstalled new version of jupyterlab-app but unfortunately I have not any 'Find' in 'Edit' menu bar. I am using ubuntu 21.04. How can I solve this problem?
![Screenshot from 2021-09-30 08-40-42](https://user-images.githubusercontent.com/65063089/135391361-ddf02ee0-8e37-4c99-bb98-b5e9c7e081c3.png)
