### ISSUE TITLE
"Access is denied." for `!pip install` command

### ISSUE THREAD

**Issue by shayandavoodii** [jupyterlab/jupyterlab_app#274]
i want to install `pdarima` package using:
```python3
!pip install pmdarima
```
also i did:
```python3
!pip install --user pmdarima
```

both of ways returned:
> Access is denied.  
 
but i installed packages by `!pip install ...` in previous version (v3.1.12-1)
How can i fix it?
JupyterLab app version : v3.1.13-1
Operation system : Windows 10

**Comment by krassowski** [comment]
The [Python Environment Customization Guide](https://github.com/jupyterlab/jupyterlab_app/blob/master/env-customization-guide.md) might help you. We cannot help without more information (such as operation system).

**Comment by shayandavoodii** [comment]
> The [Python Environment Customization Guide](https://github.com/jupyterlab/jupyterlab_app/blob/master/env-customization-guide.md) might help you. We cannot help without more information (such as operating system).

i updated the issue. It's windows 10.

**Comment by mbektas** [comment]
@shayandavoodii can you try `%pip install pmdarima` as suggested in the guide. it worked for me on Windows.

**Comment by shayandavoodii** [comment]
> @shayandavoodii can you try `%pip install pmdarima` as suggested in the guide. it worked for me on Windows.

yes it worked. is there problem with `i`?

**Comment by mbektas** [comment]
> > @shayandavoodii can you try `%pip install pmdarima` as suggested in the guide. it worked for me on Windows.
> 
> yes it worked. is there problem with `!`?

Glad to hear it worked! `%pip install` resolves to the environment the kernel is running from.
