### ISSUE TITLE
Open the same python script file at multiple tabs

### ISSUE THREAD

**Issue by dancebean** [jupyterlab/jupyterlab_app#276]
### Problem

* I would like to be able to open the same python script file (`.py`) at multiple jupyter lab tabs
* Currently, if I open a python `.py`  file in one panel, and when I drag one python `.py` file to a separated panel, the tab of the opened file will automatically be closed in the current panel.

### Proposed Solution

- [ ] When drag a python `.py` file to a panel which is separated from the panel with the file that is currently opened, both panel can have tabs that can open and edit the file at the same time.
- [ ] Add an option in the right-click contextual menu to duplicate the current opened `.py` python file.

### Additional context-
- Sometimes, we would like to look at different section of the code from the same  python `.py` file. It would be useful to be able to open two or more duplicated tab for the same file so that the user doesn't need to scroll through the same file back and forth.
- I am able to achieve this using both VSCode and Spyder IDE.

**Comment by krassowski** [comment]
You can right-click on the tab of the file and choose "New View for Python File" - please see below:

![multiple-views-demo](https://user-images.githubusercontent.com/5832902/135774028-5de93c5f-93db-46ed-8788-69dc9ce137d1.gif)

For general feature requests and bug reports regarding JupyterLab itself the main repository is a better place: https://github.com/jupyterlab/jupyterlab - if you think that it should be in the context menu of the file editor itself please search the open issues, and if you are certain it was not requested already please open one to discuss. If there is a consensus on adding it to that context menu, I can guide you on how to make a pull request to contribute.

**Comment by krassowski** [comment]
I will close this issue as this is not something which is related to jupyterlab-app, but to JupyterLab itself.
