### ISSUE TITLE
Creating venv or using existing venv.

### ISSUE THREAD

**Issue by shayandavoodii** [jupyterlab/jupyterlab_app#278]
is it possible to create virtual environment by jupyterlab app or using an existing one ?
OS : Windows 10

**Comment by krassowski** [comment]
There is already a discussion on this in https://github.com/jupyterlab/jupyterlab_app/issues/169#issuecomment-934708235. Should we close this one to consolidate discussion?

**Comment by shayandavoodii** [comment]
> There is already a discussion on this in [#169 (comment)](https://github.com/jupyterlab/jupyterlab_app/issues/169#issuecomment-934708235). Should we close this one to consolidate discussion?

Thanks for your help, although I read  [Your recommendation](https://github.com/jupyterlab/jupyterlab_app/issues/169#issuecomment-934708235) but still i don't know how to use conda envs that have been created before.
