### ISSUE TITLE
Design goals

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab_app#3]
To augment the architectural issue opened #2, I wanted to open an issue to discuss the overall design goals for an electron app. Let's start this as an issue and evolve it into a markdown doc in the readme. Some of the goals I have in mind are:

* Ability to minimize the "extra" UI to provide more working area in the app. This includes getting rid of the browser chrome and being able to move the JupyterLab menu bar to being a native menu bar.
* Access to npm on the server side to make it easier for users to manage JupyterLab extensions as npm packages, and rebuild on the fly, etc.
* Ability to offer a nice experience for double clicking on a notebook file and having it opened in the app.
* Easy management of notebook servers without using the command line. The app can automatically start/stop a local notebook server, keep track of remote servers, etc. This would allow users to seamlessly track and switch between the different servers easily.
* Integration between our keyboard handling/shortcuts and the native OS ones.

Can others add more design goals? @charnpreetsingh @rschroll

**Comment by rschroll** [comment]
I'll just note here that Juno provides half of (1), getting rid of the excess browser chrome but not nativizing the JupyterLab menu, etc., and a fairly good start on (4), with a configurable server launch system and a stored history of recent servers.

Other than these, I can't think of any must-haves from my point of view.

**Comment by ddavidebor** [comment]
> Ability to minimize the "extra" UI to provide more working area in the app. This includes getting rid of the browser chrome and being able to move the JupyterLab menu bar to being a native menu bar.

This was achieved in #42 

> Ability to offer a nice experience for double clicking on a notebook file and having it opened in the app.

Opened #51 for this

> Easy management of notebook servers without using the command line. The app can automatically start/stop a local notebook server, keep track of remote servers, etc. This would allow users to seamlessly track and switch between the different servers easily.

#48

**Comment by lucbouchard1** [comment]
Closing to reduce clutter. Design is pretty cemented at this point.
