### ISSUE TITLE
Start the notebook server in the user's home directory

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab_app#37]
Right now the server is started in the electron app directory, should probably start in the user's home directory.

**Comment by lucbouchard1** [comment]
Agreed. A couple other things,

- I think we should implement command line arguments so users can start the electron app on a particular directory, just like vscode.
- We should store the last directory the user had open so we can reopen to that directory the next time the app starts. I assume we would just add a file to the ~.jupyter directory.
- Taking that even further, vscode stores the user's window size, tabs open, etc. We should talk about implementing those as well.
