### ISSUE TITLE
Utilize native menu bar

### ISSUE THREAD

**Issue by lucbouchard1** [jupyterlab/jupyterlab_app#40]
The JupyterLab electron app will place the menu bar content in the native menu bar instead of at the top of the window. This will be a more efficient use of screen space.

**Comment by ddavidebor** [comment]
You could also go frameless, and move the three close/minimize/extend buttons in the app itself and hide both the OS frame and the native menu bar, in a similar way as VScode. 

There is free space on the right of the app to do it. Not sure if this can affect Phospor JS badly. 

![screenshot at 2017-07-02 14 03 25](https://user-images.githubusercontent.com/9055742/27769655-3f92591c-5f2f-11e7-8509-26dd0bcbe1cc.png)
