### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by lucbouchard1** [jupyterlab/jupyterlab_app#41]
In replacing the default electron menu bar with the JupyterLab menu bar (#40), I have taken away the ability to open the chrome developer tools. This is fine for the final product, but for development we should be able to start the app in debug mode using a command line argument. Debug mode should add an additional menu to the menu bar that enables the developer tools.

**Comment by ddavidebor** [comment]
We often wack this everywhere https://github.com/sindresorhus/electron-debug

Davide
