### ISSUE TITLE
File binding

### ISSUE THREAD

**Issue by ddavidebor** [jupyterlab/jupyterlab_app#51]
following #3 :

* associate ipython notebooks files with the app
  * with proper icon
* ability to open code files

**Comment by ddavidebor** [comment]
This should be assigned to a milestone

**Comment by vidartf** [comment]
Here is some Windows code I have, that might be useful: https://gist.github.com/vidartf/f5e4429d8078878405084a9a699d4d8b

**Comment by ddavidebor** [comment]
@vidartf Thank you but electron should have cross-platform APIS for this

**Comment by vidartf** [comment]
Ah, didn't know that, thanks :)
