### ISSUE TITLE
Graphical elements for distribution

### ISSUE THREAD

**Issue by ddavidebor** [jupyterlab/jupyterlab_app#67]
The following graphical elements can improve the app appearance:

- [x] NSIS sidebar, the default one is very blue
- [x] NSIS installer icon
- [x] Mac's DMG background, including retina support
- [x] Mac's DMG icon
- [x] check if Mac's app icon works well with retina devices

**Comment by nproctor** [comment]
The DMG and NSIS installer icon default to the application icon. 
On my Windows laptop, the NSIS installer doesn't have the sidebar. Could you post a screen shot?

**Comment by ddavidebor** [comment]
It should be in the last page of the wizards, looks like this:

![download](https://user-images.githubusercontent.com/9055742/28737312-37f2a15c-73ee-11e7-9a88-4aec308d86dd.png)
