### ISSUE TITLE
Appimage

### ISSUE THREAD

**Issue by ddavidebor** [jupyterlab/jupyterlab_app#72]
Build an AppImage too

**Comment by probonopd** [comment]
__electron-builder__can do it automatically.

**Comment by ddavidebor** [comment]
yeah i know still has to be tested considering the security restrictions of AppImages

**Comment by probonopd** [comment]
This is now closed but unfortunately there is still no AppImage available for download on the GitHub Releases page.

**Comment by ddavidebor** [comment]
The app still hasn't been released in it's first version (0.1)  even if it's not far away https://github.com/jupyterlab/jupyterlab_app/milestone/1

Meanwhile here you can find unofficial builds from master.

https://transfer.sh/EFk7e/jupyterlab_app_0.0.1_amd64.deb
https://transfer.sh/6BXmJ/jupyterlab_app-0.0.1.tar.gz
https://transfer.sh/YRlT9/jupyterlab_app-0.0.1.x86_64.rpm
https://transfer.sh/pCPob/jupyterlab_app-0.0.1-x86_64.AppImage

**Comment by probonopd** [comment]
Thank you very much but be aware that transfer.sh links expire after 14 days.

**Comment by matumot** [comment]
Is it possible to build AppImage distribution for JupyterLab Desktop?
AppImage Github is now available.
https://github.com/AppImage

For Windows, we can you Windows embeddable package of Python to
provide JupyterLab environment without install.
I think AppImage can be used as alternative way for Linux and macOS.
