### ISSUE TITLE
GH_TOKEN not set

### ISSUE THREAD

**Issue by ddavidebor** [jupyterlab/jupyterlab_app#94]
Builds are failing https://travis-ci.org/jupyterlab/jupyterlab_app/jobs/260434845

#87 was merged without setting GH_TOKEN

@lucbouchard1

**Comment by blink1073** [comment]
Helpful links:

https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
https://docs.travis-ci.com/user/encryption-keys/

**Comment by lucbouchard1** [comment]
Fixed. First release will be published soon.
